// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ollon.VisualStudio
{
    static class Vsix
    {
        public const string Id = "MenuCommandGeneratorPackage.Company.e073d741-3708-4806-bb00-3eb1258d91f4";
        public const string Name = "MenuCommandGeneratorPackage";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
